### ISSUE TITLE
As a <Seeker> I want to <Login using my Facebook Account>

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#14]
As a <Seeker> I want to <Login using my Facebook Account> so I can maintain a list of BUMPS that I care about.

**I'll know when this is done when I can:**
1. Login using my Facebook Account:
2. Receive an welcome email to confirm my login details
3. Confirm the terms & conditions
4. Be able to see my Facebook ID in mySettings
5. Be able to reset my password

**Comment by KenCarroll** [comment]
Have added Facebook settings (App ID +  App secret) to Firebase.
