### ISSUE TITLE
As a <Seeker> I want to <Login using my Twitter Account>

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#15]
As a <Seeker> I want to <Login using my Twitter Account> so I can maintain a list of BUMPS that I care about.

**I'll know when this is done when I can:**
1. Login using my Twitter Account:
2. Receive an welcome email to confirm my login details
3. Confirm the terms & conditions
4. Be able to see my Twitter ID in mySettings
5. Be able to reset my password

**Implementation Success Factors:**
When Setting up the APP ID in Twitter there are a number of options that need to be set. 
**1. "Enable Callback Locking" is currently unset. Should it be set?**  "Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url)"
**2. When configuring Twitter Sign-In (Authentication) the twitter settings require a callback URL.**
"Where should we return after successfully authenticating? OAuth 1.0a applications should explicitly specify their oauth_callback URL on the request token step, regardless of the value given here. To restrict your application from using callbacks, leave this field blank."
**3. Twitter settings include a Terms of Service URL.** "The URL for your application or service's terms of service. The URL will be shared with users authorizing this application."
**4. Twitter Settings have a field for the Privacy Policy URL.** "The URL for your application or service's privacy policy. The URL will be shared with users authorizing this application."
**5. Application Icon (Twitter Sign-In).** Twitter Settings. Application Icon.
Maximum size of 700k. JPG, GIF, PNG.

**Comment by KenCarroll** [comment]
Have added Twitter settings (App API key + secret) to Firebase.
