### ISSUE TITLE
get domain hosting to work

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#19]
### Description

To verify ownership of the domain, we need to add two TXT records to our DNS records in our domain registrar.  However our domain registrar system does not seem to allow two TXT records to be defined exactly as required (host + value). 
### Expected outcome
Custom Domain name correctly mapped 

### Live Demo

www.bump2solve.com
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by KenCarroll** [comment]
Have sent support request msg to Firebase for clarification of DNS TXT File settings.

**Comment by KenCarroll** [comment]
Reset and Restarted the Custom Domain Verificaiton Process (following email exchange with Firebase support): 

1. Remove all Firebase related records from your DNS provider
2. Unlink your custom domain from your current project
3. Wait about 5 to 10 minutes and re-verify your custom domain. Make sure that you copy exactly the records shown to you by your hosting console and that you follow GoDaddy's steps on how to add TXT records.

**Comment by KenCarroll** [comment]
Have set CNAME record in GoDaddy and setup Domain Forwarding. 

However, the site is still not displaying correctly!!!

Um...

**Comment by KenCarroll** [comment]
This is now resolved. Firebase suggested adding in A Records. Also chatted with GoDaddy who reviewed the settings.
