### ISSUE TITLE
Add new fields to bumps

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#3]
### Description

Currently bumps only have title and description. Add fields defined in [https://github.com/BumpConductor/OpenBUMPS/blob/master/bumps.md](url)
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by KenCarroll** [comment]
Am closing this issue. Instead it will be covered by issue #5 As a <Seeker> I want to <Edit BUMPS>
