### ISSUE TITLE
As a <Seeker> I want to <Login using my Email Address>

### ISSUE THREAD

**Issue by KenCarroll** [BumpConductor/OpenBUMPS#30]
As a **Seeker** I want to **Login** so that **I can maintain a list of BUMPS that impact me**.

**I'll know when this is done when I can:**
1. Login using my Email Address:
2. Receive an welcome email to confirm my login details
3. Confirm the terms & conditions
4. Be able to see my email address in mySettings
5. Be able to reset my password

**Comment by erols** [comment]
Done - please test and re-open if it doesn't work for you or needs enhancements
