### ISSUE TITLE
As <Product Owner> I want to help users to <Contact Us>

### ISSUE THREAD

**Issue by KenCarroll** [BumpConductor/OpenBUMPS#37]
As a **Product Owner** I want a **Contact Us page** so that **anyone can contact us**.

**I'll know when this is done when users can:**

1. Access a Contact Us option in the site menu
2. Fill in a form with their name + email address + subject + message
3. There is a captcha to stop spammers
4. A message is displayed to confirm the form has been submitted
5. The user receives an email to confirm the form has been sent
6. The product owner receives an email with the message

**Comment by KenCarroll** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub Issues](https://trello.com/c/eR9ntYI5/1-github-issues)

**Comment by erols** [comment]
Hi Ken. I think you need to add me in Trello? My username in trello is
erolsuleyman

**Comment by KenCarroll** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contact Us](https://trello.com/c/Go8DmYwx/1-contact-us)
