### ISSUE TITLE
Implement "infinite scrolling" in bumps list

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#7]
### Description
Use iron-list element to implement infinite scrolling

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by KenCarroll** [comment]
Although I like Infinite scrolling I don't think it is applicable for the BUMPS list.  It will be a good feature for scrolling through images within the context of a BUMP though e.g. looking at all the uploaded pictures related to Sugar in Food etc.  

Thoughts?

**Comment by KenCarroll** [comment]
I suggest we close this.  Instead of scrolling we will go for a traditional list pagination. Have added a UserStory for this.
