### ISSUE TITLE
As a <Seeker> I want to <view BUMPS by category>

### ISSUE THREAD

**Issue by erols** [BumpConductor/OpenBUMPS#9]
As a **Seeker** I want to be able to **view BUMPS by category** so that I can **easily find BUMPS**.

I'll know when this is done when I can:

1. View BUMPS by category
2. Add BUMPS to a category
3. Sort BUMPS by category
4. Filter BUMPS by category

**Comment by KenCarroll** [comment]
Here is one candidate list of industry categories https://developer.linkedin.com/docs/reference/industry-codes
